@echo off
echo UXM Performans Analiz ve Optimizasyon Süreci Başlatılıyor...
echo ============================================================

echo [STEP 1] Zeka Raporu ve Optimize ASM Uretiliyor...
python zekiassop.py
echo [STEP 2] Agir Siklet Optimizasyon Kurallari Uygulaniyor...
python UXM_Heavy_Asm_Optimizer.py
echo [STEP 3] Optimize Kodlar Derleniyor ve Olculuyor...
python build_optimized2.py
@echo off
rem ... önceki adımlar ...
echo [STEP 4] Orijinal ve Optimize EXE Karşılaştırılıyor (SQL Kaydı)...
python uxm_optimizer_pro.py
echo Analiz Tamamlandı. Veritabanı: optimizasyon\uxm_perf_history.db
pause